In [4]:
# Imported pandas and numpy library as pd and np respectively.

import pandas as pd
import numpy as np

In [5]:
# Made a series of random 50 numbers using the pandas library.

series = pd.Series(np.random.rand(50))

In [6]:
# Printing the series

series

0     0.109908
1     0.074922
2     0.912722
3     0.994479
4     0.797526
5     0.123182
6     0.945684
7     0.000561
8     0.917491
9     0.418241
10    0.461253
11    0.586504
12    0.791002
13    0.779284
14    0.779171
15    0.915663
16    0.315470
17    0.454763
18    0.438651
19    0.888312
20    0.501144
21    0.943965
22    0.798866
23    0.080498
24    0.866241
25    0.102946
26    0.827170
27    0.325992
28    0.929510
29    0.520901
30    0.553766
31    0.826615
32    0.304641
33    0.746385
34    0.255480
35    0.570414
36    0.133064
37    0.965012
38    0.333419
39    0.797956
40    0.401470
41    0.150271
42    0.509705
43    0.600008
44    0.466568
45    0.136102
46    0.709242
47    0.487910
48    0.252660
49    0.061083
dtype: float64

In [7]:
# This shows the datatype like it is a series or a dataframe.

type(series)

pandas.core.series.Series

In [30]:
# Making a Dataframe of random numbers of 500 rows and 10 columns using the pandas Library and also allocating the index of the Dataframe using the .arange() function which is similar to the range() function.

dataframe = pd.DataFrame(np.random.rand(500, 10), index = np.arange(1, 501))

In [31]:
# Printing the Dataframe

dataframe

,0,1,2,3,4,5,6,7,8,9
1,0.400172,0.092910,0.699485,0.015966,0.485098,0.694161,0.589844,0.374302,0.300049,0.876479
2,0.743343,0.670624,0.092405,0.891937,0.537497,0.995707,0.679337,0.207401,0.832717,0.066730
3,0.462334,0.461027,0.114334,0.574410,0.895075,0.465082,0.427028,0.943920,0.795661,0.312247
4,0.893300,0.725723,0.698815,0.360182,0.290733,0.114648,0.393530,0.790885,0.776004,0.525949
5,0.650714,0.173891,0.329020,0.966420,0.116627,0.891455,0.176338,0.338468,0.067254,0.316511
...,...,...,...,...,...,...,...,...,...,...
496,0.710591,0.681946,0.740170,0.890694,0.184294,0.301229,0.542864,0.227668,0.023480,0.571522
497,0.824790,0.867699,0.350874,0.933962,0.323193,0.879713,0.770632,0.830348,0.713611,0.660029
498,0.874087,0.759880,0.495409,0.274833,0.841921,0.432650,0.744874,0.932349,0.370106,0.683071
499,0.691554,0.206502,0.298596,0.935811,0.898506,0.467685,0.838956,0.167498,0.148311,0.262422
500,0.705313,0.183679,0.709816,0.324004,0.363833,0.063949,0.850193,0.104908,0.452088,0.981534

In [10]:
# We have again made a Dataframe with random numbers with 500 rows and 10 columns but, this time we have not explicitly allocated the indexing of the rows.

dataframe = pd.DataFrame(np.random.rand(500, 10))

In [11]:
# Printing the Dataframe.

dataframe

,0,1,2,3,4,5,6,7,8,9
0,0.237025,0.285790,0.340552,0.481790,0.966704,0.080491,0.524996,0.206900,0.350233,0.065036
1,0.895272,0.001941,0.725776,0.837901,0.679380,0.334322,0.670905,0.568879,0.063644,0.925012
2,0.575839,0.159236,0.994167,0.554157,0.034477,0.025919,0.520631,0.007365,0.079196,0.541076
3,0.059569,0.686866,0.233376,0.939464,0.176841,0.550266,0.373610,0.400938,0.545650,0.991997
4,0.972704,0.877381,0.014250,0.679127,0.576786,0.378391,0.044495,0.224998,0.961814,0.609980
...,...,...,...,...,...,...,...,...,...,...
495,0.498806,0.079210,0.886692,0.624185,0.725094,0.353695,0.452408,0.067116,0.148820,0.816675
496,0.724475,0.822429,0.513123,0.025467,0.855345,0.355381,0.262563,0.954176,0.439875,0.333112
497,0.383558,0.078976,0.164843,0.001843,0.546891,0.348215,0.719339,0.079979,0.057137,0.693137
498,0.358781,0.083175,0.972247,0.561733,0.090445,0.535387,0.670591,0.779878,0.928704,0.263982
499,0.789368,0.288761,0.407675,0.239296,0.320331,0.413891,0.957368,0.630602,0.668067,0.373627

In [12]:
# It shows the type of the varible like if it is a dataframe or series.

type(dataframe)

pandas.core.frame.DataFrame

In [13]:
# This shows the top five rows along with their respective columns.

dataframe.head()

,0,1,2,3,4,5,6,7,8,9
0,0.237025,0.285790,0.340552,0.481790,0.966704,0.080491,0.524996,0.206900,0.350233,0.065036
1,0.895272,0.001941,0.725776,0.837901,0.679380,0.334322,0.670905,0.568879,0.063644,0.925012
2,0.575839,0.159236,0.994167,0.554157,0.034477,0.025919,0.520631,0.007365,0.079196,0.541076
3,0.059569,0.686866,0.233376,0.939464,0.176841,0.550266,0.373610,0.400938,0.545650,0.991997
4,0.972704,0.877381,0.014250,0.679127,0.576786,0.378391,0.044495,0.224998,0.961814,0.609980

In [14]:
# This shows some information about the Dataframe.

dataframe.describe()

,0,1,2,3,4,5,6,7,8,9
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,0.479152,0.486162,0.485985,0.477164,0.511776,0.511696,0.498313,0.504423,0.505496,0.516512
std,0.298075,0.292164,0.287567,0.293926,0.294025,0.283699,0.287011,0.288208,0.293414,0.285563
min,0.000376,0.000633,0.001415,0.001553,0.003535,0.000920,0.000355,0.002652,0.000336,0.002637
25%,0.234143,0.227078,0.242003,0.220575,0.252859,0.270880,0.259309,0.257405,0.250686,0.265841
50%,0.458596,0.480818,0.462172,0.462355,0.506703,0.517537,0.503198,0.530751,0.491666,0.509370
75%,0.745558,0.736085,0.727323,0.731584,0.761499,0.761467,0.733267,0.753327,0.769146,0.763208
max,0.993643,0.999139,0.999151,0.999903,0.999939,0.999764,0.996239,0.998150,0.999342,0.999128

In [15]:
# This shows some information about the Series.

series.describe()

count    50.000000
mean      0.537276
std       0.304432
min       0.000561
25%       0.307348
50%       0.515303
75%       0.798639
max       0.994479
dtype: float64

In [17]:
# This shows the datatypes in the Dataframe.

dataframe.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8    float64
9    float64
dtype: object

In [18]:
# Changing the data at the index [0][0] to "Jyotibrat"

dataframe[0][0] = "Jyotibrat"

C:\Users\gamin\AppData\Local\Temp\ipykernel_22648\3828925137.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe[0][0] = "Jyotibrat"
C:\Users\gamin\AppData\Local\Temp\ipykernel_22648\3828925137.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Jyotibrat' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  dataframe[0][0] = "Jyotibrat"

In [19]:
# This shows the top five rows along with the their respective columns.

dataframe.head()

,0,1,2,3,4,5,6,7,8,9
0,Jyotibrat,0.285790,0.340552,0.481790,0.966704,0.080491,0.524996,0.206900,0.350233,0.065036
1,0.895272,0.001941,0.725776,0.837901,0.679380,0.334322,0.670905,0.568879,0.063644,0.925012
2,0.575839,0.159236,0.994167,0.554157,0.034477,0.025919,0.520631,0.007365,0.079196,0.541076
3,0.059569,0.686866,0.233376,0.939464,0.176841,0.550266,0.373610,0.400938,0.545650,0.991997
4,0.972704,0.877381,0.014250,0.679127,0.576786,0.378391,0.044495,0.224998,0.961814,0.609980

In [20]:
# This shows the datatypes of Dataframe.

dataframe.dtypes

0     object
1    float64
2    float64
3    float64
4    float64
5    float64
6    float64
7    float64
8    float64
9    float64
dtype: object

In [21]:
# This shows the total index of the Dataframe.

dataframe.index

RangeIndex(start=0, stop=500, step=1)

In [23]:
# This shows the total columns of the Dataframe.

dataframe.columns

RangeIndex(start=0, stop=10, step=1)

In [24]:
# This converts the Dataframe to a numpy array.

dataframe.to_numpy

<bound method DataFrame.to_numpy of              0         1         2         3         4         5         6  \
0    Jyotibrat  0.285790  0.340552  0.481790  0.966704  0.080491  0.524996
1     0.895272  0.001941  0.725776  0.837901  0.679380  0.334322  0.670905
2     0.575839  0.159236  0.994167  0.554157  0.034477  0.025919  0.520631
3     0.059569  0.686866  0.233376  0.939464  0.176841  0.550266  0.373610
4     0.972704  0.877381  0.014250  0.679127  0.576786  0.378391  0.044495
..         ...       ...       ...       ...       ...       ...       ...
495   0.498806  0.079210  0.886692  0.624185  0.725094  0.353695  0.452408
496   0.724475  0.822429  0.513123  0.025467  0.855345  0.355381  0.262563
497   0.383558  0.078976  0.164843  0.001843  0.546891  0.348215  0.719339
498   0.358781  0.083175  0.972247  0.561733  0.090445  0.535387  0.670591
499   0.789368  0.288761  0.407675  0.239296  0.320331  0.413891  0.957368

            7         8         9
0    0.206900  0.350233  0.065036
1    0.568879  0.063644  0.925012
2    0.007365  0.079196  0.541076
3    0.400938  0.545650  0.991997
4    0.224998  0.961814  0.609980
..        ...       ...       ...
495  0.067116  0.148820  0.816675
496  0.954176  0.439875  0.333112
497  0.079979  0.057137  0.693137
498  0.779878  0.928704  0.263982
499  0.630602  0.668067  0.373627

[500 rows x 10 columns]>

In [25]:
# Changing the data at the index[0][0] to 0.55

dataframe[0][0] = 0.55

In [26]:
# This shows the top five rows along with the their respective columns.

dataframe.head()

,0,1,2,3,4,5,6,7,8,9
0,0.55,0.285790,0.340552,0.481790,0.966704,0.080491,0.524996,0.206900,0.350233,0.065036
1,0.895272,0.001941,0.725776,0.837901,0.679380,0.334322,0.670905,0.568879,0.063644,0.925012
2,0.575839,0.159236,0.994167,0.554157,0.034477,0.025919,0.520631,0.007365,0.079196,0.541076
3,0.059569,0.686866,0.233376,0.939464,0.176841,0.550266,0.373610,0.400938,0.545650,0.991997
4,0.972704,0.877381,0.014250,0.679127,0.576786,0.378391,0.044495,0.224998,0.961814,0.609980

In [27]:
# This transposes the rows and columns basically means it changes the rows to columns and vice versa.

dataframe.T

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
0,0.55,0.895272,0.575839,0.059569,0.972704,0.044169,0.340625,0.041745,0.113154,0.334301,...,0.180226,0.756981,0.354185,0.652555,0.26232,0.498806,0.724475,0.383558,0.358781,0.789368
1,0.28579,0.001941,0.159236,0.686866,0.877381,0.816265,0.567352,0.150194,0.734934,0.722113,...,0.279219,0.50879,0.196338,0.826198,0.303719,0.07921,0.822429,0.078976,0.083175,0.288761
2,0.340552,0.725776,0.994167,0.233376,0.01425,0.838421,0.670004,0.140312,0.059059,0.14646,...,0.781604,0.593665,0.055007,0.905898,0.109554,0.886692,0.513123,0.164843,0.972247,0.407675
3,0.48179,0.837901,0.554157,0.939464,0.679127,0.650379,0.298292,0.09555,0.639145,0.564952,...,0.67253,0.297834,0.068221,0.652896,0.309103,0.624185,0.025467,0.001843,0.561733,0.239296
4,0.966704,0.67938,0.034477,0.176841,0.576786,0.826763,0.740439,0.293933,0.355995,0.089371,...,0.794919,0.101358,0.179617,0.808698,0.132347,0.725094,0.855345,0.546891,0.090445,0.320331
5,0.080491,0.334322,0.025919,0.550266,0.378391,0.83124,0.099444,0.391721,0.627008,0.381557,...,0.770949,0.537181,0.867255,0.200241,0.754484,0.353695,0.355381,0.348215,0.535387,0.413891
6,0.524996,0.670905,0.520631,0.37361,0.044495,0.407455,0.085087,0.640399,0.698064,0.140223,...,0.700468,0.920425,0.368263,0.209836,0.105209,0.452408,0.262563,0.719339,0.670591,0.957368
7,0.2069,0.568879,0.007365,0.400938,0.224998,0.727632,0.609296,0.528201,0.040885,0.884823,...,0.454293,0.891672,0.855984,0.893296,0.628242,0.067116,0.954176,0.079979,0.779878,0.630602
8,0.350233,0.063644,0.079196,0.54565,0.961814,0.895414,0.196362,0.585339,0.205527,0.471382,...,0.35103,0.397988,0.998394,0.469596,0.02519,0.14882,0.439875,0.057137,0.928704,0.668067
9,0.065036,0.925012,0.541076,0.991997,0.60998,0.478516,0.492317,0.831379,0.883779,0.873302,...,0.522506,0.820924,0.519662,0.925823,0.271187,0.816675,0.333112,0.693137,0.263982,0.373627