In [1]:
# Imported pandas and numpy library as pd and np respectively.

import pandas as pd
import numpy as np

In [9]:
df = pd.DataFrame(np.random.randint(0, 100, size=(3,2)))
df

    0   1
0  60  57
1   1  53
2  75  49

In [10]:
df.describe()

               0     1
count   3.000000   3.0
mean   45.333333  53.0
std    39.119475   4.0
min     1.000000  49.0
25%    30.500000  51.0
50%    60.000000  53.0
75%    67.500000  55.0
max    75.000000  57.0

In [11]:
df.mean()

0    45.333333
1    53.000000
dtype: float64

In [12]:
df.corr()

         0        1
0  1.00000 -0.19172
1 -0.19172  1.00000

In [13]:
df.count()

0    3
1    3
dtype: int64

In [14]:
df.max()

0    75
1    57
dtype: int32

In [15]:
df.min()

0     1
1    49
dtype: int32

In [16]:
df.median()

0    60.0
1    53.0
dtype: float64

In [17]:
df.std()

0    39.119475
1     4.000000
dtype: float64