In [1]:
# Imported pandas and numpy library as pd and np respectively.

import pandas as pd
import numpy as np

In [6]:
# Creating a Dataframe of random numbers with 100 rows and 5 columns.

dataframe = pd.DataFrame(np.random.rand(100, 5))

In [7]:
# Printing the Dataframe

dataframe

           0         1         2         3         4
0   0.361391  0.528244  0.613971  0.344405  0.714542
1   0.972997  0.474298  0.770747  0.598272  0.175492
2   0.869607  0.445064  0.391649  0.965881  0.070651
3   0.941374  0.735814  0.788813  0.398245  0.548156
4   0.329538  0.078064  0.180919  0.617539  0.715086
..       ...       ...       ...       ...       ...
95  0.443510  0.528200  0.401576  0.993504  0.296133
96  0.483174  0.371554  0.401007  0.454811  0.679908
97  0.804928  0.196982  0.898848  0.028499  0.276274
98  0.247857  0.562604  0.217982  0.470616  0.252155
99  0.448699  0.986843  0.116082  0.480936  0.500186

[100 rows x 5 columns]

In [8]:
# This functions gives the number of rows and columns.

dataframe.shape

(100, 5)

In [10]:
# This function gives some information of the dataframe.

dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       100 non-null    float64
 1   1       100 non-null    float64
 2   2       100 non-null    float64
 3   3       100 non-null    float64
 4   4       100 non-null    float64
dtypes: float64(5)
memory usage: 4.0 KB

In [11]:
# Creating a Dataframe consisting of 'names', 'toy' and 'born' and printing the dataframe.

df = pd.DataFrame({"name": ['Alfred', 'batman', 'Alfred'],
                        "toy": [np.nan, 'Batmobile', 'Bullwhip'],
                        "born": [pd.NaT, pd.Timestamp("1940-04-25"),
                        pd.NaT]})
df

     name        toy       born
0  Alfred        NaN        NaT
1  batman  Batmobile 1940-04-25
2  Alfred   Bullwhip        NaT

In [14]:
# This functions gives the count of the elements present in the column of the dataframe but by default it does not count the values like 'NaN' and 'NaT' but, if we put the argument 'dropna=False' then, it also gives the count of those elements too.

df['toy'].value_counts(dropna=False)

toy
NaN          1
Batmobile    1
Bullwhip     1
Name: count, dtype: int64

In [15]:
# This function gives the count of elements and does count elements like 'NaN' and 'NaT'.

df['toy'].value_counts()

toy
Batmobile    1
Bullwhip     1
Name: count, dtype: int64

In [18]:
# This shows all the value which are null in value in the dataset.

df.isnull()

    name    toy   born
0  False   True   True
1  False  False  False
2  False  False   True

In [19]:
# It just gives the opposite result of the 'isnull' function.

df.notnull()

   name    toy   born
0  True  False  False
1  True   True   True
2  True   True  False